export interface Drivers {
    id:number;
    name:string;
    country:string;
    podiums:number;
    points:number;
    team_color:string;
    profile:string;
    team_name:string;
    gp:number;
    champion:number;
    drivernb:number;
    dob:string;
    picture:string;
    flag:string;
    join_f1:number;
    age:number;
    city:string;
    teamsid:number;
    championshipid:number;
}
